name: Link checker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem update --system 3.3.3
        gem install bundler
        bundle install

    - name: Build site
      run: | 
        bundle exec jekyll build

    - name: Check links
      run: |
          bundle exec htmlproofer \
            --assume-extension .html \
            --ignore-missing-alt \
            --ignore-empty-alt \
            --no-check-external-hash \
            --allow-missing-href \
            --typhoeus '{"connecttimeout": 10, "timeout": 30, "accept_encoding": "zstd,br,gzip,deflate"}' \
            --hydra '{"max_concurrency": 1}' \
            --ignore-files '/_site\/post/,/about.html/,/blog-recommendation-in-vespa/,/blog-search-application-in-vespa/,/blog-recommendation-with-neural-network-models/' \
            --ignore-urls '/slack.vespa.ai/,/twitter.com/,/localhost:8080/,/www.linkedin.com/,/cord19.vespa.ai/,/disqus.com/,/disqus_thread/,/docs.vespa.ai/playground/,/facebook.com/sharer/,/arxiv.org/,/hub.docker.com/r/vespaengine/vespa/tags/,/www.wowthemes.net/' \
            --swap-urls '(https\://github.com.*/master/.*)#.*:\1,(https\://github.com.*/main/.*)#.*:\1,(https\://github.com.*/blob/.*)#.*:\1' \
            _site
