name: Vespa Blog Search Feed
on:
  push:
    branches: [ master ]

env:
  DATA_PLANE_PUBLIC_KEY: ${{ secrets.VESPA_TEAM_DATA_PLANE_PUBLIC_CERT }}
  DATA_PLANE_PRIVATE_KEY: ${{ secrets.VESPA_TEAM_DATA_PLANE_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Build site
      run: |
        bundle exec jekyll build -p _plugins-vespafeed

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Feed site
      run: |
        pip3 install PyYAML mmh3 requests html5lib beautifulsoup4 markdownify tiktoken
        ./feed_to_vespa.py _config.yml

    - name: Feed paragraphs site
      run: |
        ./feed-split.py blog_index.json https://blog.vespa.ai questions.jsonl
        ./feed_to_vespa.py _paragraphs_config.yml

    - name: Feed suggestions 
      run: |
        ./feed_to_vespa.py _suggestions_config.yml
